language: c
compiler: gcc
install:
- bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.install
script:
- bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.script
after_success:
- bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.after_success

